# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - release:ignore
    authors:
      - octocat
  categories:
    - title: ⭐ Important changes
      labels:
        - release:important
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
        - release:breaking
    - title: 🆕 New features and detections 🎉
      labels:
        - enhancement
        - release:new-detection
        - release:new-feature
    - title: 🪦 Rule removals
      labels:
        - release:remove-rules
    - title: 🧰 Other Changes
      labels:
        - "*"
