name: Check PR dependencies
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check Dependencies
    permissions:
      pull-requests: read # Reason: To check PRs for dependencies.
    steps:
      - uses: gregsdennis/dependencies-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
