name: Mark stale issues

on:
  schedule:
  - cron: "0 0 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:

    runs-on: ubuntu-latest
    if: github.repository == 'coreruleset/coreruleset'

    steps:
    - uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been open 90 days waiting for feedback. Remove the stale label or comment, or this will be closed in 90 days'
        stale-issue-label: 'Stale issue'
        days-before-stale: 90
        days-before-close: 90
        only-issue-labels: ':hourglass_flowing_sand: awaiting feedback'
