name: Regression Tests

on:
  push:
    paths:
      - 'rules/**'
      - 'tests/**'
      - '.github/**'
  pull_request:
    paths:
      - 'rules/**'
      - 'tests/**'
      - 'util/**'
      - '.github/**'
  merge_group:

# Pin tool versions to prevent problems
env:
  GO_FTW_VERSION: '0.6.4'

jobs:
  regression:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modsec_version: [modsec2-apache]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.2

      - name: "Install dependencies"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download -R coreruleset/go-ftw "v${{ env.GO_FTW_VERSION }}" \
            -p "ftw_${{ env.GO_FTW_VERSION }}_linux_amd64.tar.gz" -O - | tar -xzvf - ftw

      - name: "Run tests for ${{ matrix.modsec_version }}"
        env:
          FTW_LOGFILE: './tests/logs/${{ matrix.modsec_version }}/error.log'
        run: |
          mkdir -p "tests/logs/${{ matrix.modsec_version }}/{nginx,apache2}"
          chmod -R o+rw "tests/logs"
          docker-compose -f ./tests/docker-compose.yml up -d "${{ matrix.modsec_version }}"
          docker-compose -f ./tests/docker-compose.yml logs
          [ "$(docker inspect ${{ matrix.modsec_version }} --format='{{.State.Running}}')" = "true" ]
          ./ftw check -d tests/regression/tests
          ./ftw run -d tests/regression/tests --show-failures-only

      - name: "Change permissions if failed"
        if: failure()
        run: |
            # we want to get the audit log, so change permissions (file is only for root on docker)
            sudo chmod 644 tests/logs/${{ matrix.modsec_version }}/modsec_audit.log

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        if: failure()
        with:
          name: waf-logs
          path: tests/logs/${{ matrix.modsec_version }}

      - name: Clean docker-compose
        run: |
          docker-compose -f ./tests/docker-compose.yml stop "${{ matrix.modsec_version }}"
          docker-compose -f ./tests/docker-compose.yml down
