name: Regression Tests

on:
  push:
    paths:
      - 'rules/**'
      - 'tests/**'
      - '.github/**'
  pull_request:
    paths:
      - 'rules/**'
      - 'tests/**'
      - 'util/**'
      - '.github/**'

jobs:
  regression:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_target: [modsec2-apache, modsec3-nginx, coraza-go]
      fail-fast: false # Continues to run other targets even if one fails
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_FTW_VERSION: '0.6.3'
        run: |
          gh release download -R coreruleset/go-ftw v${GO_FTW_VERSION} -p "ftw_${GO_FTW_VERSION}_linux_amd64.tar.gz" -O - | tar -xzvf - ftw

      - name: "Run tests for ${{ matrix.test_target }}"
        run: |
          mkdir -p tests/logs/${{ matrix.test_target }}/{nginx,apache2,coraza}
          docker-compose -f ./tests/docker-compose.yml up -d "${{ matrix.test_target }}"
          docker-compose -f ./tests/docker-compose.yml logs
          [ $(docker inspect ${{ matrix.test_target }} --format='{{.State.Running}}') = 'true' ]
          ./ftw check -d tests/regression/tests
          ./ftw run -d tests/regression/tests --show-failures-only
        env:
          FTW_LOGFILE: './tests/logs/${{ matrix.test_target }}/error.log'

      - name: "Change permissions if failed"
        if: failure()
        run: |
            # we want to get the audit log, so change permissions (file is only for root on docker)
            sudo chmod 644 tests/logs/${{ matrix.test_target }}/modsec_audit.log

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: waf-logs
          path: tests/logs/${{ matrix.test_target }}

      - name: Clean docker-compose
        run: |
          docker-compose -f ./tests/docker-compose.yml stop "${{ matrix.test_target }}"
          docker-compose -f ./tests/docker-compose.yml down
